author:              "Author name here"
copyright:           "2019 Author name here"
github:              "githubuser/radicle-lang"
license:             BSD3
maintainer:          "example@example.com"
name:                radicle-lang
version:             0.0.0.4

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/radicle-lang#readme>

dependencies:
- base >= 4.7 && < 5

data-files:
- ../rad/**/*.rad

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - cryptonite
    - generics-eot
    - megaparsec
    - mmorph
    - mtl
    - pointed
    - prettyprinter
    - prettyprinter-ansi-terminal
    - process
    - protolude
    - QuickCheck
    - quickcheck-instances
    - serialise
    - scientific
    - template-haskell
    - text
    - time
    - uuid
    - unordered-containers
    - vector

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    dependencies:
    - containers
    - cryptonite
    - interpolate
    - megaparsec
    - process
    - protolude
    - QuickCheck
    - quickcheck-instances
    - radicle-lang
    - scientific
    - serialise
    - string-qq
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - time
    build-tools:
    - tasty-discover
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]

default-extensions:
- ConstraintKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
