name:                radicle-repl
version:             0.1.0.0
github:              "githubuser/radicle-repl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/radicle-repl#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- radicle-lang

library:
  source-dirs: src
  dependencies:
    - ansi-terminal
    - bytestring
    - containers
    - directory
    - filepath
    - haskeline
    - prettyprinter
    - process
    - text
    - time

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    dependencies:
    - containers
    - cryptonite
    - interpolate
    - megaparsec
    - process
    - protolude
    - QuickCheck
    - radicle-lang
    - radicle-repl
    - scientific
    - serialise
    - string-qq
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - time
    build-tools:
    - tasty-discover
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]

default-extensions:
- ConstraintKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- TypeFamilies
